/**
 * Doorstep website embed (HOR-283).
 *
 * A self-contained, unbranded name+mobile capture form an agent pastes on
 * their own site. It:
 *   - renders inline into [data-doorstep-embed] containers, so it inherits
 *     the host page's CSS and looks like the agent's own form (no Horace
 *     branding anywhere — the brand invisibility invariant);
 *   - sets the first-party _riq_aid (1y) and _riq_sid (30m) cookies, using
 *     the SAME names/attributes as tracker.ts so the two share one device
 *     identity on the agent's domain — this is what lets later page views be
 *     attributed to the captured contact;
 *   - POSTs to /api/embed/capture on the Horace host the script was served
 *     from (derived from the script's own src — never hardcoded).
 *
 * Install (generated by the WPA, HOR-285):
 *   <div data-doorstep-embed></div>
 *   <script src="https://<host>/embed.min.js" data-key="<snippet_key>" defer></script>
 *
 * Optional per-container overrides: data-key, data-button, data-success,
 * data-name-label, data-mobile-label.
 */

interface DoorstepResult {
  ok?: boolean
  error?: string
  field?: string
}

;(function () {
  const SELF =
    (document.currentScript as HTMLScriptElement | null) ||
    (document.querySelector('script[src*="embed.min.js"]') as HTMLScriptElement | null)

  const API_ORIGIN = (() => {
    try {
      return SELF ? new URL(SELF.src).origin : ''
    } catch {
      return ''
    }
  })()
  const SCRIPT_KEY = SELF?.getAttribute('data-key') || ''

  const COOKIE_AID = '_riq_aid'
  const COOKIE_SID = '_riq_sid'
  const SESSION_S = 30 * 60

  function getCookie(name: string): string | null {
    const m = document.cookie.match(new RegExp('(?:^|; )' + name + '=([^;]*)'))
    return m ? decodeURIComponent(m[1]) : null
  }

  function setCookie(name: string, value: string, maxAge: number): void {
    document.cookie = `${name}=${encodeURIComponent(value)}; max-age=${maxAge}; path=/; SameSite=Lax${
      location.protocol === 'https:' ? '; Secure' : ''
    }`
  }

  function genId(): string {
    if (typeof crypto !== 'undefined' && crypto.randomUUID) return crypto.randomUUID()
    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
      const r = (Math.random() * 16) | 0
      return (c === 'x' ? r : (r & 0x3) | 0x8).toString(16)
    })
  }

  function anonymousId(): string {
    let aid = getCookie(COOKIE_AID)
    if (!aid) {
      aid = genId()
      setCookie(COOKIE_AID, aid, 365 * 24 * 3600)
    }
    return aid
  }

  function sessionId(): string {
    const sid = getCookie(COOKIE_SID) || genId()
    setCookie(COOKIE_SID, sid, SESSION_S) // refresh expiry
    return sid
  }

  function esc(s: string): string {
    return s.replace(
      /[&<>"]/g,
      (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c] as string,
    )
  }

  function renderInto(container: HTMLElement): void {
    const key = container.getAttribute('data-key') || SCRIPT_KEY
    if (!key) {
      console.warn('[doorstep] no data-key set — embed disabled')
      return
    }
    if (container.getAttribute('data-doorstep-rendered') === '1') return
    container.setAttribute('data-doorstep-rendered', '1')

    const buttonLabel = esc(container.getAttribute('data-button') || 'Submit')
    const successMsg = esc(container.getAttribute('data-success') || 'Thanks — we’ll be in touch.')
    const nameLabel = esc(container.getAttribute('data-name-label') || 'Name')
    const mobileLabel = esc(container.getAttribute('data-mobile-label') || 'Mobile')
    const uid = 'ds_' + Math.random().toString(36).slice(2, 8)

    container.innerHTML = `
      <form class="doorstep-form" novalidate>
        <div class="doorstep-field">
          <label for="${uid}_name">${nameLabel}</label>
          <input id="${uid}_name" name="name" type="text" autocomplete="name" required />
        </div>
        <div class="doorstep-field">
          <label for="${uid}_mobile">${mobileLabel}</label>
          <input id="${uid}_mobile" name="mobile" type="tel" inputmode="tel" autocomplete="tel" required />
        </div>
        <div aria-hidden="true" style="position:absolute;left:-9999px;width:1px;height:1px;overflow:hidden">
          <label>Leave this empty<input type="text" name="hp_email" tabindex="-1" autocomplete="off" /></label>
        </div>
        <button type="submit" class="doorstep-submit">${buttonLabel}</button>
        <p class="doorstep-status" role="status" aria-live="polite" style="display:none"></p>
      </form>
    `

    const form = container.querySelector('form') as HTMLFormElement
    const status = container.querySelector('.doorstep-status') as HTMLElement
    const submitBtn = container.querySelector('.doorstep-submit') as HTMLButtonElement

    function showStatus(msg: string): void {
      status.textContent = msg
      status.style.display = msg ? '' : 'none'
    }

    form.addEventListener('submit', (e) => {
      e.preventDefault()
      const fd = new FormData(form)
      const name = String(fd.get('name') || '').trim()
      const mobile = String(fd.get('mobile') || '').trim()
      const hp = String(fd.get('hp_email') || '')

      if (!name) return showStatus('Please enter your name.')
      if (!mobile) return showStatus('Please enter your mobile number.')

      const original = submitBtn.textContent
      submitBtn.disabled = true
      submitBtn.textContent = '…'
      showStatus('')

      fetch(`${API_ORIGIN}/api/embed/capture`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          snippet_key: key,
          name,
          mobile,
          anonymous_id: anonymousId(),
          tracker_session_id: sessionId(),
          page_url: location.href,
          hp_email: hp,
        }),
        credentials: 'omit',
        keepalive: true,
      })
        .then(async (res) => {
          const data = (await res.json().catch(() => ({}))) as DoorstepResult
          if (res.ok && data.ok) {
            container.innerHTML = `<p class="doorstep-success">${successMsg}</p>`
            return
          }
          submitBtn.disabled = false
          submitBtn.textContent = original
          // Only surface validation messages; never leak internal/origin errors.
          showStatus(
            data.field && data.error ? data.error : 'Something went wrong. Please try again.',
          )
        })
        .catch(() => {
          submitBtn.disabled = false
          submitBtn.textContent = original
          showStatus('Network error. Please try again.')
        })
    })
  }

  function boot(): void {
    const containers = Array.prototype.slice.call(
      document.querySelectorAll('[data-doorstep-embed]'),
    ) as HTMLElement[]
    if (containers.length === 0) {
      console.warn('[doorstep] no [data-doorstep-embed] container found on the page')
      return
    }
    containers.forEach(renderInto)
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', boot, { once: true })
  } else {
    boot()
  }
})()
