import { createAdminClient } from '@/lib/supabase/admin'
import { postToAlertVolumeChannel } from '@/lib/notifications/slack'
import { vapidSubject } from './vapid'
import { getEffectiveScoreThresholdForAgent } from '@/lib/sensitivity/thresholds'

const DEDUP_MINUTES = 30
const VOLUME_CAP_PER_24H = 8
const REVIEW_WINDOW_MS = 24 * 60 * 60 * 1000

// HOR-146 widened notification_log.type to include the inspection variants
// in the same constraint set as the existing alerts.
// HOR-153 (this file) adds the matching send helpers below.
export type AlertType =
  | 'alert_score_threshold'
  | 'alert_form_submit'
  | 'alert_return_visit'
  | 'alert_inspection_capture'
  | 'alert_inspection_revisit'
  | 'alert_embed_capture'
  | 'alert_portal_enquiry'

const PUSH_ALERT_TYPES: AlertType[] = [
  'alert_score_threshold',
  'alert_form_submit',
  'alert_return_visit',
  'alert_inspection_capture',
  'alert_inspection_revisit',
  'alert_embed_capture',
  'alert_portal_enquiry',
]

// notification_log.type's autogenerated TS literal union lags HOR-146
// until `database.types.ts` regenerates. Cast at insert sites until then.
type LegacyAlertType =
  | 'alert_score_threshold'
  | 'alert_form_submit'
  | 'alert_return_visit'

interface PushPayload {
  title: string
  body: string
  url: string
  tag: string
}

async function sendWebPush(endpoint: string, p256dh: string, auth: string, payload: PushPayload): Promise<boolean> {
  const webpush = await import('web-push')

  // Prefer the client/subscription key (NEXT_PUBLIC_*): that's the key the
  // browser subscribed with, so the server must sign with the same one or the
  // push service rejects it. Falling back to VAPID_PUBLIC_KEY makes a mis-set
  // or swapped VAPID_PUBLIC_KEY non-fatal (HOR-296).
  const vapidPublic  = process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY || process.env.VAPID_PUBLIC_KEY
  const vapidPrivate = process.env.VAPID_PRIVATE_KEY

  if (!vapidPublic || !vapidPrivate) {
    console.warn('[push] VAPID keys not set — skipping push')
    return false
  }

  try {
    webpush.setVapidDetails(vapidSubject(), vapidPublic, vapidPrivate)
  } catch (err) {
    // Malformed VAPID config (e.g. a bare-email VAPID_EMAIL) — don't let it
    // throw through dispatch and 500 the whole alert path (HOR-296).
    console.error('[push] invalid VAPID config — skipping push', err)
    return false
  }

  try {
    await webpush.sendNotification(
      { endpoint, keys: { p256dh, auth } },
      JSON.stringify(payload),
    )
    return true
  } catch (err: unknown) {
    const status = (err as { statusCode?: number }).statusCode
    if (status === 410 || status === 404) {
      // Subscription expired — clean it up
      const admin = createAdminClient()
      await admin.from('push_subscriptions').delete().eq('endpoint', endpoint)
    } else {
      console.error('[push] send failed', err)
    }
    return false
  }
}

async function isRecentlySent(agentId: string, contactId: string | null, type: AlertType): Promise<boolean> {
  const admin = createAdminClient()
  const since = new Date(Date.now() - DEDUP_MINUTES * 60_000).toISOString()
  const q = admin
    .from('notification_log')
    .select('*', { count: 'exact', head: true })
    .eq('agent_id', agentId)
    .eq('type', type)
    .gte('sent_at', since)

  if (contactId) q.eq('contact_id', contactId)

  const { count } = await q
  return (count ?? 0) > 0
}

async function logAlert(
  agentId: string,
  contactId: string | null,
  type: AlertType,
  display?: { title: string; body: string; url: string },
  // HOR-350: optional property this moment is about. Tagged at flag time for
  // property-subject moments (e.g. inspection capture) so the property detail
  // "Surfaced in your Stream" link resolves precisely.
  propertyId?: string | null,
): Promise<void> {
  const admin = createAdminClient()
  await admin.from('notification_log').insert({
    agent_id: agentId,
    contact_id: contactId,
    // Cast: HOR-146 widened the DB constraint to accept the inspection
    // variants; database.types.ts regen will catch up after the schema
    // PR merges. Drop the cast then.
    type: type as LegacyAlertType,
    title: display?.title ?? null,
    body: display?.body ?? null,
    url: display?.url ?? null,
    // Cast: property_id (HOR-350) lands in database.types.ts on the next regen.
    ...(propertyId ? { property_id: propertyId } : {}),
  } as never)
}

/**
 * Push a payload to every active subscription for an agent.
 *
 * Exported so non-alert flows (e.g. Core Markets import-complete,
 * HOR-193) can reuse the cleanup-on-expired-subscription behaviour
 * without going through dispatchPushAlert's dedup + volume-cap path.
 * Direct callers are responsible for their own logging.
 */
export async function pushToAgent(agentId: string, payload: PushPayload): Promise<void> {
  const admin = createAdminClient()
  const { data: subs } = await admin
    .from('push_subscriptions')
    .select('endpoint, p256dh, auth')
    .eq('agent_id', agentId)

  if (!subs || subs.length === 0) return

  await Promise.all(subs.map((s) => sendWebPush(s.endpoint, s.p256dh, s.auth, payload)))
}

async function pushesInLast24h(agentId: string): Promise<number> {
  const admin = createAdminClient()
  const since = new Date(Date.now() - REVIEW_WINDOW_MS).toISOString()
  const { count } = await admin
    .from('notification_log')
    .select('*', { count: 'exact', head: true })
    .eq('agent_id', agentId)
    .in('type', PUSH_ALERT_TYPES)
    .gte('sent_at', since)
  return count ?? 0
}

async function alreadyFlaggedForReview(agentId: string): Promise<boolean> {
  const admin = createAdminClient()
  const since = new Date(Date.now() - REVIEW_WINDOW_MS).toISOString()
  const { count } = await admin
    .from('notification_log')
    .select('*', { count: 'exact', head: true })
    .eq('agent_id', agentId)
    .eq('type', 'volume_review')
    .gte('sent_at', since)
  return (count ?? 0) > 0
}

async function emitVolumeReview(agentId: string, countAfter: number): Promise<void> {
  if (await alreadyFlaggedForReview(agentId)) return

  const admin = createAdminClient()
  const { data: agent } = await admin
    .from('agents')
    .select('first_name, last_name, workspaces(name)')
    .eq('id', agentId)
    .maybeSingle<{ first_name: string | null; last_name: string | null; workspaces: { name: string | null } | null }>()

  const agentName = agent
    ? [agent.first_name, agent.last_name].filter(Boolean).join(' ').trim() || agentId
    : agentId
  const workspaceName = agent?.workspaces?.name ?? 'unknown workspace'

  const text =
    `Alert volume cap hit — *${agentName}* (${workspaceName}) has had *${countAfter} pushes* ` +
    `in the last 24h (cap is ${VOLUME_CAP_PER_24H}). The alert design is likely mis-tuned for this agent. ` +
    `<https://linear.app/gohorace/project/alerts-and-notifications-02f66872bea5|Alerts & Notifications>`

  await postToAlertVolumeChannel(text)

  await admin.from('notification_log').insert({
    agent_id: agentId,
    contact_id: null,
    type: 'volume_review',
  })
}

async function dispatchPushAlert(args: {
  agentId: string
  contactId: string
  type: AlertType
  payload: PushPayload
  /** HOR-350: property this moment is about, when known at flag time. */
  propertyId?: string | null
}): Promise<void> {
  const { agentId, contactId, type, payload, propertyId } = args

  if (await isRecentlySent(agentId, contactId, type)) return

  await pushToAgent(agentId, payload)
  await logAlert(agentId, contactId, type, {
    title: payload.title,
    body: payload.body,
    url: payload.url,
  }, propertyId)

  const countAfter = await pushesInLast24h(agentId)
  if (countAfter > VOLUME_CAP_PER_24H) {
    await emitVolumeReview(agentId, countAfter)
  }
}

export async function sendScoreThresholdAlert(
  agentId: string,
  contactId: string,
  contactName: string,
  scoreAfter: number,
  scoreBefore: number,
): Promise<void> {
  const admin = createAdminClient()
  const threshold = await getEffectiveScoreThresholdForAgent(admin, agentId)
  if (!(scoreBefore < threshold && scoreAfter >= threshold)) return

  const firstName = contactName.split(' ')[0]
  await dispatchPushAlert({
    agentId,
    contactId,
    type: 'alert_score_threshold',
    payload: {
      title: `${firstName} is gathering momentum`,
      body: `Horace's been watching ${firstName} — the signal just got stronger. Worth a look.`,
      url: `/contacts/${contactId}`,
      tag: `score-${contactId}`,
    },
  })
}

export async function sendFormSubmitAlert(
  agentId: string,
  contactId: string,
  contactName: string,
  formName: string | null,
): Promise<void> {
  const firstName = contactName.split(' ')[0]
  const title = formName
    ? `${firstName} just submitted "${formName}"`
    : `${firstName} just got in touch`
  await dispatchPushAlert({
    agentId,
    contactId,
    type: 'alert_form_submit',
    payload: {
      title,
      body: `Horace has ${firstName}'s details now. Worth a call while it's warm.`,
      url: `/contacts/${contactId}`,
      tag: `form-${contactId}`,
    },
  })
}

export async function sendReturnVisitAlert(
  agentId: string,
  contactId: string,
  contactName: string,
): Promise<void> {
  const firstName = contactName.split(' ')[0]
  await dispatchPushAlert({
    agentId,
    contactId,
    type: 'alert_return_visit',
    payload: {
      title: `${firstName} is back on your site`,
      body: `Horace just spotted ${firstName} returning. Worth a quick hello.`,
      url: `/contacts/${contactId}`,
      tag: `return-${contactId}`,
    },
  })
}

// ─────────────────────────────────────────────────────────────────────────────
// HOR-153 — Doorstep inspection alerts
//
// `alert_inspection_capture` fires the moment a prospect submits the
// public capture form at /i/<token> (HOR-152). Body uses the brief's
// verbatim copy: "Horace just met <Name> at <Address>".
//
// `alert_inspection_revisit` fires when a captured contact comes back
// to the agent's tracked site within 30 days of their scan. The
// scoring engine variant in HOR-154 prefers this over the generic
// return-visit copy.
//
// No sign-off on push per docs/alerts-copy-standards.md — push is too
// short. The brief's "Seize the moment — Horace" stays on the digest
// email only.
// ─────────────────────────────────────────────────────────────────────────────

export async function sendInspectionCaptureAlert(
  agentId: string,
  contactId: string,
  contactName: string,
  /**
   * Short address. The stitch_contact_from_inspection RPC already returns
   * this shape ("123 Smith Street, Surry Hills"); callers pass it through
   * verbatim.
   */
  address: string,
  /**
   * HOR-350: the inspection's property. An inspection capture is the clearest
   * property-subject moment ("Horace just met X at <address>"), so we tag it so
   * the property page links straight back to this row.
   */
  propertyId?: string | null,
): Promise<void> {
  const firstName = contactName.split(' ')[0]
  await dispatchPushAlert({
    agentId,
    contactId,
    type: 'alert_inspection_capture',
    payload: {
      title: `Horace just met ${firstName} at ${address}`,
      body: `Worth a quick hello before they leave.`,
      url: `/contacts/${contactId}`,
      tag: `inspection-capture-${contactId}`,
    },
    propertyId,
  })
}

/**
 * HOR-284 — Doorstep website-embed capture alert.
 *
 * Fires when a prospect submits the invisible same-origin embed form on the
 * agent's own site. Copy is the brief's verbatim, deliberately un-named line:
 * the angle is "Horace will watch what they do next" (the behavioural-signal
 * payoff of a same-origin tagged device), not "you just met someone". Deduped
 * 30min like the rest; the embed endpoint can call it on every submit.
 */
export async function sendEmbedCaptureAlert(
  agentId: string,
  contactId: string,
): Promise<void> {
  await dispatchPushAlert({
    agentId,
    contactId,
    type: 'alert_embed_capture',
    payload: {
      title: `Someone just left their details on your website`,
      body: `Horace is watching what they do next.`,
      url: `/contacts/${contactId}`,
      tag: `embed-capture-${contactId}`,
    },
  })
}

// ─────────────────────────────────────────────────────────────────────────────
// HOR-233 — Portal enquiry alert
//
// Fires when a buyer submits an enquiry on REA / Domain and the inbound
// router (lib/inbound/router.ts) resolves it to a contact. Copy is the
// brief's verbatim line for `portal_enquiry_received` (docs/alerts-copy-
// standards.md → HOR-78): names the contact, the listing and the source,
// and teaches the reply-via-Horace behaviour that binds the device.
//
// The in-app feed entry mirrors this push verbatim (logAlert stores
// title/body, which to-stream-moment renders as headline/editorial).
// ─────────────────────────────────────────────────────────────────────────────

function portalLabel(sourcePortal: string | null): string {
  switch (sourcePortal) {
    case 'rea':    return 'REA'
    case 'domain': return 'Domain'
    default:       return 'a portal'
  }
}

export async function sendPortalEnquiryAlert(
  agentId: string,
  contactId: string,
  /** Enquirer's name as parsed from the email; may be empty for anonymous enquirers. */
  contactName: string | null,
  /** Listing the enquiry was about, e.g. "12 Maple St". */
  listingAddress: string | null,
  sourcePortal: string | null,
): Promise<void> {
  const firstName = (contactName ?? '').trim().split(' ')[0] || null
  const listing = listingAddress?.trim() || 'your listing'
  const via = portalLabel(sourcePortal)

  const title = firstName
    ? `${firstName} just enquired on ${listing} via ${via}`
    : `New enquiry on ${listing} via ${via}`
  const body = firstName
    ? `Horace has set ${firstName} up — first reply via Horace and he'll start watching properly.`
    : `Horace has set them up — first reply via Horace and he'll start watching properly.`

  await dispatchPushAlert({
    agentId,
    contactId,
    type: 'alert_portal_enquiry',
    payload: {
      title,
      body,
      url: `/contacts/${contactId}`,
      tag: `portal-enquiry-${contactId}`,
    },
  })
}

export async function sendInspectionRevisitAlert(
  agentId: string,
  contactId: string,
  contactName: string,
  /**
   * Street name only (no number, no suburb) — the title reads
   * "<Name> from the <street_name> open home is back".
   */
  street: string,
  /**
   * Short verb phrase computed by the scoring engine — e.g.
   * "viewing sold results", "back on your appraisal page".
   * Used as the body without further punctuation; helper adds the period.
   */
  behaviour: string,
): Promise<void> {
  const firstName = contactName.split(' ')[0]
  await dispatchPushAlert({
    agentId,
    contactId,
    type: 'alert_inspection_revisit',
    payload: {
      title: `${firstName} from the ${street} open home is back`,
      body: `${behaviour}. Worth a call.`,
      url: `/contacts/${contactId}`,
      tag: `inspection-revisit-${contactId}`,
    },
  })
}
